/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
Copyright (C) 2012-2015 Sensia Software LLC. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.impl.sensor;

import net.opengis.swe.v20.DataBlock;
import org.sensorhub.api.common.IEventListener;
import org.sensorhub.api.common.IEventPublisher;
import org.sensorhub.api.data.IDataProducer;
import org.sensorhub.api.sensor.ISensor;
import org.sensorhub.api.sensor.ISensorDataInterface;
import org.sensorhub.api.sensor.ISensorModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.vast.util.Asserts;


/**
 * <p>
 * Class providing default implementation of common sensor data interface
 * API methods. By default, storage is unsupported.
 * </p>
 *
 * @author Alex Robin
 * @param <SensorType> Type of parent sensor
 * @since Nov 2, 2014
 */
public abstract class AbstractSensorOutput<SensorType extends IDataProducer> implements ISensorDataInterface
{
    protected static final String ERROR_NO_STORAGE = "Data storage is not supported by driver ";
    protected final SensorType parentSensor;
    protected final IEventPublisher eventHandler;
    protected final String name;
    protected final Logger log;
    protected DataBlock latestRecord;
    protected long latestRecordTime = Long.MIN_VALUE;
    
    
    public AbstractSensorOutput(ISensorModule<?> parentSensor)
    {
        this(null, parentSensor);
    }
    
    
    /**
     * Constructs a new sensor output with the given name and attached to the
     * provided sensor module.<br/>
     * Events generated by this output will be published using the parent sensor's
     * event handler.
     * @param name output name
     * @param parentSensor parent sensor instance
     */
    @SuppressWarnings("unchecked")
    public AbstractSensorOutput(String name, ISensorModule<?> parentSensor)
    {
        this(name, (SensorType)parentSensor, null);
    }
    
    
    /**
     * Constructs a new sensor output with the given name and attached to the
     * provided sensor module.<br/>
     * Events generated by this output will be published using the provided handler.
     * @param name output name
     * @param parentSensor parent sensor instance
     * @param eventHandler event handler to use to publish events
     */
    public AbstractSensorOutput(String name, SensorType parentSensor, IEventPublisher eventHandler)
    {
        this(name, parentSensor, eventHandler, null);
    }
    
    
    /**
     * Constructs a new sensor output with the given name and attached to the
     * provided sensor module.<br/>
     * @param name
     * @param parentSensor
     * @param eventHandler
     * @param log
     */
    public AbstractSensorOutput(String name, SensorType parentSensor, IEventPublisher eventHandler, Logger log)
    {
        this.name = name;
        this.parentSensor = Asserts.checkNotNull(parentSensor, ISensor.class);
                
        if (log == null)
            this.log = LoggerFactory.getLogger(getClass().getCanonicalName());
        else
            this.log = log;
        
        // use event handler of the parent sensor
        if (eventHandler == null && parentSensor instanceof ISensorModule)
        {
            String procedureID = parentSensor.getUniqueIdentifier();
            this.eventHandler = ((ISensorModule<?>)parentSensor).getParentHub().getEventBus().getPublisher(procedureID);
        }
        else
        {
            Asserts.checkNotNull(eventHandler, IEventPublisher.class);
            this.eventHandler = eventHandler;
        }
    }
    
    
    protected void stop()
    {
        // do nothing by default
    }
    
    
    @Override
    public SensorType getParentProducer()
    {
        return parentSensor;
    }
    
    
    /**
     * @deprecated use {@link #getParentProducer()} instead
     * @return parent sensor 
     */
    @Deprecated(forRemoval=true)
    public SensorType getParentModule()
    {
        return getParentProducer();
    }
    
    
    @Override
    public String getName()
    {
        return name;
    }


    @Override
    public boolean isEnabled()
    {
        return true;
    }


    @Override
    public DataBlock getLatestRecord()
    {
        return latestRecord;
    }
    
    
    @Override
    public long getLatestRecordTime()
    {
        return latestRecordTime;
    }
    
    
    @Override
    public void registerListener(IEventListener listener)
    {
        eventHandler.registerListener(listener);
    }


    @Override
    public void unregisterListener(IEventListener listener)
    {
        eventHandler.unregisterListener(listener);
    }

}
