/***************************** BEGIN LICENSE BLOCK ***************************

The contents of this file are subject to the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one
at http://mozilla.org/MPL/2.0/.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
for the specific language governing rights and limitations under the License.
 
Copyright (C) 2019 Sensia Software LLC. All Rights Reserved.
 
******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.api.common;

import java.util.concurrent.Flow;
import java.util.function.Predicate;


/**
 * <p>
 * Extension of IEventProducer that adds support for back pressure via new
 * Java 9 Flow.Publisher interface.
 * </p>
 *
 * @author Alex Robin
 * @param <T> Type of events generated by this producer
 * @date Feb 19, 2019
 */
@SuppressWarnings("rawtypes")
public interface IEventProducer2<T extends Event> extends Flow.Publisher<T>, IEventProducer
{
    
    public void subscribe(Flow.Subscriber<? super T> subscriber, Predicate<? super T> filter);
}
